### ISSUE TITLE
HTTPSConnectionPool(host='cloud-api.yandex.net', port=443) on Android

### ISSUE THREAD

**Issue by mrTokar** [ivknv/yadisk#30]
Использую вашу библиотеку для создания мобильного приложения. При разработке на любом ПК устройстве все отлично работает. В коде этого приложения мне необходимо проверить валидность токена. Делаю я это с помощью метода `yadisk.YaDisk.check_token()`. Когда интепритатор пытается выполнить эту команду в уже скомпилированном приложении на Android девайсе, поднимается исключение ConnectionError.

**Лог ошибки**:
```
[DEBUG  ] [Starting new HTTPS connection (2)] cloud-api.yandex.net:443
[DEBUG  ] [Starting new HTTPS connection (3)] cloud-api.yandex.net:443
[DEBUG  ] [Starting new HTTPS connection (4)] cloud-api.yandex.net:443
[DEBUG  ] [Starting new HTTPS connection (5)] cloud-api.yandex.net:443
[DEBUG  ] [Starting new HTTPS connection (6)] cloud-api.yandex.net:443
[ERROR  ] [Container   ] HTTPSConnectionPool(host='cloud-api.yandex.net', port=443): Max retries exceeded with url: /v1/disk/operations/0000 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x737c2ce230>: Failed to resolve 'cloud-api.yandex.net' ([Errno 7] No address associated with hostname)"))
Traceback (most recent call last):
  File "/home/egor/Documents/TodaCheck/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/todacheck/arm64-v8a/urllib3/connection.py", line 203, in _new_conn
  File "/home/egor/Documents/TodaCheck/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/todacheck/arm64-v8a/urllib3/util/connection.py", line 60, in create_connection
  File "/home/egor/Documents/TodaCheck/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/python3/arm64-v8a__ndk_target_21/python3/Lib/socket.py", line 955, in getaddrinfo
socket.gaierror: [Errno 7] No address associated with hostname

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/egor/Documents/TodaCheck/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/todacheck/arm64-v8a/urllib3/connectionpool.py", line 790, in urlopen
  File "/home/egor/Documents/TodaCheck/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/todacheck/arm64-v8a/urllib3/connectionpool.py", line 491, in _make_request
  File "/home/egor/Documents/TodaCheck/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/todacheck/arm64-v8a/urllib3/connectionpool.py", line 467, in _make_request
  File "/home/egor/Documents/TodaCheck/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/todacheck/arm64-v8a/urllib3/connectionpool.py", line 1092, in _validate_conn
  File "/home/egor/Documents/TodaCheck/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/todacheck/arm64-v8a/urllib3/connection.py", line 611, in connect
  File "/home/egor/Documents/TodaCheck/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/todacheck/arm64-v8a/urllib3/connection.py", line 210, in _new_conn
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x737c2ce230>: Failed to resolve 'cloud-api.yandex.net' ([Errno 7] No address associated with hostname)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/egor/Documents/TodaCheck/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/todacheck/arm64-v8a/requests/adapters.py", line 486, in send
  File "/home/egor/Documents/TodaCheck/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/todacheck/arm64-v8a/urllib3/connectionpool.py", line 844, in urlopen
  File "/home/egor/Documents/TodaCheck/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/todacheck/arm64-v8a/urllib3/util/retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cloud-api.yandex.net', port=443): Max retries exceeded with url: /v1/disk/operations/0000 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x737c2ce230>: Failed to resolve 'cloud-api.yandex.net' ([Errno 7] No address associated with hostname)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/egor/Documents/TodaCheck/.buildozer/android/app/View/container.py", line 48, in connect_to_data
  File "/home/egor/Documents/TodaCheck/.buildozer/android/app/dbmanage.py", line 15, in __init__
  File "/home/egor/Documents/TodaCheck/.buildozer/android/app/diskmanage.py", line 35, in __init__
  File "/home/egor/Documents/TodaCheck/.buildozer/android/app/diskmanage.py", line 49, in read_token
  File "/home/egor/Documents/TodaCheck/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/todacheck/arm64-v8a/yadisk/yadisk.py", line 396, in check_token
  File "/home/egor/Documents/TodaCheck/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/todacheck/arm64-v8a/yadisk/yadisk.py", line 1658, in _get_operation_status
  File "/home/egor/Documents/TodaCheck/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/todacheck/arm64-v8a/yadisk/api/api_request.py", line 124, in send
  File "/home/egor/Documents/TodaCheck/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/todacheck/arm64-v8a/yadisk/utils.py", line 99, in auto_retry
  File "/home/egor/Documents/TodaCheck/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/todacheck/arm64-v8a/yadisk/utils.py", line 96, in auto_retry
  File "/home/egor/Documents/TodaCheck/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/todacheck/arm64-v8a/yadisk/api/api_request.py", line 110, in _attempt
  File "/home/egor/Documents/TodaCheck/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/todacheck/arm64-v8a/requests/sessions.py", line 703, in send
  File "/home/egor/Documents/TodaCheck/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/todacheck/arm64-v8a/requests/adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cloud-api.yandex.net', port=443): Max retries exceeded with url: /v1/disk/operations/0000 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x737c2ce230>: Failed to resolve 'cloud-api.yandex.net' ([Errno 7] No address associated with hostname)"))
```

**Versions**

    OS: Android 13
    Python: 3.10.12
    yadisk: 1.3.2

Также я провал подключаться к разным DNS серверам, но ошибка все равно остается. После этого я решил проверить смогу ли я вообще подключиться к этому серверу `cloud-api.yandex.net` через браузер. Итог такой же: на ПК сайт грузит нормально и возвращает json объект, а на Android  ничего не грузит. Как возможно решить эту проблему?

**Comment by mrTokar** [comment]
Да, это полностью решило мою проблему. Совсем забыл про предоставление доступа приложению.
