### ISSUE TITLE
[Bug] grant_type not in POST при отправке кода подтверждения

### ISSUE THREAD

**Issue by desperadik** [ivknv/yadisk#40]
grant_type not in POST при отправке кода подтверждения

```
def main():
    client = yadisk.Client("***", "****")
    with client:
        print(client.get_code_url())
        code = input("Enter the confirmation code: ")
        response = client.get_token(code)
    client.token = response.access_token

    if client.check_token():
        print("Successfully received token!")
    else:
        print("Something went wrong. Not sure how though...")
```

Получаем:

```
Traceback (most recent call last):
  File "/home/des/sandbox/test_sandbox.py", line 37, in <module>
    main()
  File "/home/des/sandbox/test_sandbox.py", line 23, in main
    response = client.get_token(code)
  File "/home/des/.virtualenvs/test/lib/python3.10/site-packages/yadisk/client.py", line 380, in get_token
    request.send()
  File "/home/des/.virtualenvs/test/lib/python3.10/site-packages/yadisk/api/api_request.py", line 158, in send
    auto_retry(self._attempt, self.n_retries, self.retry_interval)
  File "/home/des/.virtualenvs/test/lib/python3.10/site-packages/yadisk/utils.py", line 95, in auto_retry
    return func()
  File "/home/des/.virtualenvs/test/lib/python3.10/site-packages/yadisk/api/api_request.py", line 136, in _attempt
    raise self.response.get_exception()
yadisk.exceptions.BadRequestError: grant_type not in POST (<empty> / invalid_request)

```

Должны получить словарь с токеном

 - ОС: Ubuntu 22.04
 - Версия библиотеки `yadisk`:  2.0.0
 - Версия Python: 3.10

**Comment by desperadik** [comment]
Close. В версии 2.0.1 данный проблемы нет.
