### ISSUE TITLE
[Bug] Не импортируется

### ISSUE THREAD

**Issue by xpoison52** [ivknv/yadisk#49]
**Опишите баг**
После обновления библиотека не импортируется
Traceback (most recent call last):
  File "z:\xxi\xx.py", line 12, in <module>
    import yadisk
  File "C:\Users\xx\AppData\Roaming\Python\Python312\site-packages\yadisk\__init__.py", line 19, in <module>
    from . import objects, exceptions, utils, types
  File "C:\Users\xx\AppData\Roaming\Python\Python312\site-packages\yadisk\utils.py", line 23, in <module>   
    from .objects import ErrorObject
ModuleNotFoundError: No module named 'yadisk.objects'

**Действия по воспроизведению бага**
import yadisk

**Ожидаемое поведение**
Импорт...

**Информация о вашей системе (заполните следующую информацию):**
 - ОС: Windows
 - Версия библиотеки `yadisk`: 3.0.0
 - Версия Python: 3.12.4

**Дополнительая информация**
Нет

**Comment by ivknv** [comment]
Понял в чём дело, сейчас поправлю.

**Comment by ivknv** [comment]
Исправил в новой версии.

**Comment by xpoison52** [comment]
> Исправил в новой версии.

Спасибо!
