### ISSUE TITLE
[Bug] yadisk.exceptions.UnauthorizedError: Не авторизован. (Unauthorized / UnauthorizedError)

### ISSUE THREAD

**Issue by Zapzatron** [ivknv/yadisk#54]
**Опишите баг**
Периодически API возвращает Unauthorized. 
Это ограничение от API Яндекс.Диска? Если да, то где их можно увидеть?

**Действия по воспроизведению бага**
```python
import asyncio
import yadisk


async def get_yadisk_async_client():
    async with yadisk.AsyncClient(token=yandex_disk_api_token) as yadisk_client:
        yield yadisk_client


async def check_token(yadisk_client_):
    token_check_result = await yadisk_client_.check_token()
    if not token_check_result:
        raise Exception(f"Неверный токен для доступа к Яндекс.Диску")
    return token_check_result


async def main():
    test_num = 30

    async for yadisk_client__ in get_yadisk_async_client():
        for i in range(1, test_num + 1):
            # 1
            print(f"{i} check_token: {await check_token(yadisk_client__)}")
            # Иногда вызывается Exception(f"Неверный токен для доступа к Яндекс.Диску"), так как возвращается False.
            # GET https://cloud-api.yandex.net/v1/disk/operations/0000
            # {'timeout': (10.0, 15.0), 'headers': {'content-type': 'application/x-www-form-urlencoded', 'authorization': 'OAuth y0_...'}, 'data': None, 'params': {'fields': 'status'}}
            # От API приходит: {'message': 'Не авторизован.', 'description': 'Unauthorized', 'error': 'UnauthorizedError'}

            # 2
            # print(f"{i} is_dir: {await yadisk_client__.is_dir(r'app:/backup')}")
            # GET https://cloud-api.yandex.net/v1/disk/resources
            # {'timeout': (10.0, 15.0), 'headers': {'content-type': 'application/x-www-form-urlencoded', 'authorization': 'OAuth y0_...'}, 'data': None, 'params': {'path': 'app:/backup', 'fields': 'type'}}
            # От API приходит: {'message': 'Не авторизован.', 'description': 'Unauthorized', 'error': 'UnauthorizedError'}


if __name__ == "__main__":
    asyncio.run(main())
```

**Ожидаемое поведение**
Выполнение кода без ошибок.

**Информация о вашей системе (заполните следующую информацию):**
 - ОС: Windows 10
 - Версия библиотеки `yadisk`: yadisk[async_defaults]==3.1.0
 - Версия Python: 3.11.9

**Comment by ivknv** [comment]
Ошибка не воспроизводится. Похоже на временное поведение серверов Яндекса. В прошлом встречался с подобными ошибками (случайные `UnauthorizedError` в том числе), более того, по собственным наблюдениям, время от времени (но очень редко) некоторые запросы могут вообще не выполняться, но возвращать при этом статус 200.

Только что прогнал тесты и как раз столкнулся с примером такого поведения: после успешного `publish()` иногда публичная ссылка не появляется.

Попробуйте воспроизвести со своей стороны еще раз, если ошибки пропали, значит это сервера виноваты. Другого объяснения ошибки у меня пока нет.

**Comment by Zapzatron** [comment]
Всё также получаю `yadisk.exceptions.UnauthorizedError: Не авторизован. (Unauthorized / UnauthorizedError)`

**Comment by Zapzatron** [comment]
```python
1 check_token: True
2 check_token: True
3 check_token: True
4 check_token: True
5 check_token: True
6 check_token: True
7 check_token: True
8 check_token: True
9 check_token: True
10 check_token: True
11 check_token: True
12 check_token: True
13 check_token: True
14 check_token: True
15 check_token: True
16 check_token: True
17 check_token: True
18 check_token: True
19 check_token: True
20 check_token: True
21 check_token: True
22 check_token: True
23 check_token: True
24 check_token: True
25 check_token: True
26 check_token: True
27 check_token: True
28 check_token: True
29 check_token: True
30 check_token: True
31 check_token: True
32 check_token: True
------------------------------------------------------------------------------------------------------------------------
[02-11-2024 21:28:47] Ошибка:
Traceback (most recent call last):
  File "F:\Games\Programming_Projects\Python\Zapzatron_Club\Zapzatron_API\source\general\function_operation.py", line 61, in func_retry
    func_return = await func_run(func, params)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Games\Programming_Projects\Python\Zapzatron_Club\Zapzatron_API\source\general\function_operation.py", line 11, in func_run
    func_response = await func(**params)
                    ^^^^^^^^^^^^^^^^^^^^
  File "F:\Games\Programming_Projects\Python\Zapzatron_Club\Zapzatron_API\local\tests\ya_disk_many_requests.py", line 19, in check_token
    raise Exception(f"Неверный токен для доступа к Яндекс.Диску")
Exception: Неверный токен для доступа к Яндекс.Диску
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
[02-11-2024 21:28:52] Ошибка:
Прошло времени: 0:00:05
{
   "check_token | Неверный токен для доступа к Яндекс.Диску": {'count': 1}
}
------------------------------------------------------------------------------------------------------------------------
33 check_token: True
34 check_token: True
35 check_token: True
36 check_token: True
37 check_token: True
38 check_token: True
39 check_token: True
40 check_token: True
41 check_token: True
42 check_token: True
43 check_token: True
44 check_token: True
45 check_token: True
------------------------------------------------------------------------------------------------------------------------
[02-11-2024 21:28:59] Ошибка:
Прошло времени: 0:00:05
{
   "check_token | Неверный токен для доступа к Яндекс.Диску": {'count': 1}
}
------------------------------------------------------------------------------------------------------------------------
46 check_token: True
47 check_token: True
48 check_token: True
49 check_token: True
50 check_token: True
51 check_token: True
52 check_token: True
53 check_token: True
54 check_token: True
55 check_token: True
56 check_token: True
57 check_token: True
58 check_token: True
59 check_token: True
60 check_token: True
61 check_token: True
62 check_token: True
63 check_token: True
64 check_token: True
65 check_token: True
66 check_token: True
67 check_token: True
68 check_token: True
69 check_token: True
70 check_token: True
71 check_token: True
72 check_token: True
73 check_token: True
74 check_token: True
75 check_token: True
76 check_token: True
77 check_token: True
78 check_token: True
79 check_token: True
80 check_token: True
81 check_token: True
82 check_token: True
83 check_token: True
------------------------------------------------------------------------------------------------------------------------
[02-11-2024 21:29:09] Ошибка:
Прошло времени: 0:00:05
{
   "check_token | Неверный токен для доступа к Яндекс.Диску": {'count': 1}
}
------------------------------------------------------------------------------------------------------------------------
84 check_token: True
85 check_token: True
86 check_token: True
87 check_token: True
88 check_token: True
89 check_token: True
90 check_token: True
91 check_token: True
92 check_token: True
------------------------------------------------------------------------------------------------------------------------
[02-11-2024 21:29:15] Ошибка:
Прошло времени: 0:00:05
{
   "check_token | Неверный токен для доступа к Яндекс.Диску": {'count': 1}
}
------------------------------------------------------------------------------------------------------------------------
93 check_token: True
94 check_token: True
95 check_token: True
96 check_token: True
97 check_token: True
98 check_token: True
99 check_token: True
100 check_token: True
```
Тут поможет наверно только тот же обход, что я использовал для YDB, просто несколько раз переотправлять запрос при ошибке.

**Comment by ivknv** [comment]
Я правильно понимаю, что последний вывод вы получили с помощью несколько отличающегося от изначально приведенного кода в issue (судя по сообщению об ошибке)?

**Comment by Zapzatron** [comment]
Да последний вывод был немного с изменённым кодом. Я добавил функцию переотправки запроса для check_token().

**Comment by ivknv** [comment]
> Да, последний вывод был немного с изменённым кодом. Я добавил функцию переотправки запроса для check_token().

Все равно странно, спустя тысячи итераций, так и не удалось поймать ошибку. У вас получалось воспроизвести проблему с помощью изначально приведенного кода? Насколько часто по времени она вообще проявляется?

> Проблема этого способа в том, что нужно вызывать функции не напрямую, а передавать в функцию для переотправки.

Для этого уже есть встроенный в библиотеку механизм (параметры `n_retries`, `retry_interval`, `retry_on` и функция `utils.async_auto_retry()`).

**Comment by Zapzatron** [comment]
С помощью приведенного кода также периодически появляется эта ошибка.

**Comment by ivknv** [comment]
Похоже на проблему какой-то отдельной группы серверов. Максимум, что можно с этим сделать, это делать ограниченное число повторных запросов при получении ошибки, например так:

```python
await client.check_token(retry_on=(yadisk.exceptions.UnauthorizedError,), n_retries=10)
```

**Comment by Zapzatron** [comment]
Спасибо
